### ISSUE TITLE
com.google.cloud.logging.logback.LoggingAppender flush is too slow

### ISSUE THREAD

**Issue by kunieda-o** [googleapis/java-logging-logback#133]
I have a project running Java in an app engine which uses com.google.cloud.logging.logback.LoggingAppender to output log like as below.

https://cloud.google.com/logging/docs/setup/java

I found that the latency of log.error output is around 100ms. This means, if the app output error logs too many then app-engine would scale up.

Our app connect to some external services. When those services sometimes respond error, the app output error logs.

Does anyone know how to cope with it?

I expected that flushLevel=OFF would resolve this issue, but OFF=ALL by below method. https://github.com/googleapis/java-logging-logback/blob/0.116.0/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L336-L355

Sorry for my multi post.

https://stackoverflow.com/questions/62786760/q-gae-stackdriver-java-logback-error-logging-too-slow

I contacted Google Support Case and they told me to create an issue about this case.

**Comment by simonz130** [comment]
I don't see anything in code where the code behaves differently when we log errors with regular messages.
Can you confirm whether the issue with flush is happening when you log to stderr or also when you log to stdout?
Also, it would be great if you could share a simple repro so we can try to reproduce it faster.

**Comment by kunieda-o** [comment]
@simonz130 Thank you for your response.
I'll create the reproducer.
For now, I haven't yet checked when log to stderr or stdout.

**Comment by kunieda-o** [comment]
@simonz130 
I created the reproducer.
Could you please have a look at it?

https://github.com/kunieda-o/log-flush-too-slow

**Comment by Daniel-Sanche** [comment]
Thanks for the detailed issue report. I agree that flush level OFF should turn off all auto-flushing. I opened a PR to address this here: https://github.com/googleapis/java-logging-logback/pull/319

**Comment by Daniel-Sanche** [comment]
This issue should now be fixed, but I'll keep this open until it is released to be safe

**Comment by Daniel-Sanche** [comment]
I just tested with the new version and confirmed it works as expected on `0.120.0-alpha`. Closing this now, but let me know if you want to continue the discussion
