### ISSUE TITLE
Logback-Core SonarIQ vulnerability - sonatype-2021-1175

### ISSUE THREAD

**Issue by cfernandezmu** [googleapis/java-logging-logback#539]
Hi Team

we have identify a vulnerability level 8 on the logback-Core in Sonatype, this vulnerability looks like being carry over in all the version post 1.2.3, can you please review it and confirm what version will be remediate it?

![image](https://user-images.githubusercontent.com/49128042/133400142-783a30e2-6965-48dc-b3ea-5dff952a90fa.png)

**Comment by simonz130** [comment]
This is fixed now - base dependency for logback jar is 1.2.6 (latest w/o vulnerability). Closing this ticket.

**Comment by cfernandezmu** [comment]
Thanks @simonz130
