### ISSUE TITLE
Error while debugging locally

### ISSUE THREAD

**Issue by pvmraghunandan** [googleapis/java-logging-logback#599]
Getting below error when trying to execute the sample to test out Cloud Logging.

```Logging system failed to initialize using configuration from 'null'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@24:14 - RuntimeException in Action for tag [appender] java.lang.NullPointerException
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:179)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:232)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:73)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:282)```

Currently authenticated using ``` gcloud auth application-default login 
```

I think the issue could be due to MetadataConfig which is using VM Metadata Endpoint which is invalid in standalone machine. How to make it work?

**Comment by minherz** [comment]
@pvmraghunandan can you please confirm that in your local execution you use the logback configuration which enforces a fixed resource type in opposite to automatically discovered resource?

**Comment by pvmraghunandan** [comment]
thanks @minherz for the update

**Comment by shivankawasthi11** [comment]
Tried the workaround by removing resourceType parameter, logs are not getting appended to cloud logging

**Comment by minherz** [comment]
Thank you for the prompt response. I've tried to run a Quickstart sample that can be found in the [repo](https://github.com/googleapis/java-logging-logback/blob/main/samples/snippets/src/main/java/com/example/logging/logback/Quickstart.java) and can see logs stored in Cloud Logging.
Do you receive any error or other indication? It is important to understand that the logs will be appended to a Google Cloud project id that is configured in the Google client logging library. The value of the project id is usually read from `GOOGLE_CLOUD_PROJECT` environment variable or, if the variable is not set, from Cloud SDK configuration.
You can check what project id is configured on your client by running:

```bash
gcloud config get-value core/project
```

Please, explore logs in the appropriate project to verify that nothing was written to Cloud Logging.

**Comment by shivankawasthi11** [comment]
Yes, it worked when I set the env variable ```GOOGLE_CLOUD_PROJECT``` from google cloud shell. I am able to see logs in logs explorer. However, this is not working when code is running on my local machine.

**Comment by pvmraghunandan** [comment]
Like other SDKs, we are running below command which uses ADC.

`gcloud auth application-default login`

Should we only use service account to make it work in local?

**Comment by minherz** [comment]
This should work with client libraries instead of setting the `GOOGLE_APPLICATION_CREDENTIALS`. However, it still requires setting `GOOGLE_CLOUD_PROJECT` and to make sure that the credentials you are authenticating using `gcloud auth application-default` has proper permissions for writing logs to that project.

**Comment by minherz** [comment]
Can you check whether the problem can be reproduced with the latest versions of the logback (0.122.5) and logging libraries (3.5.1)?
Thank you.

**Comment by pvmraghunandan** [comment]
@minherz sure. I will cross check and update the results soon

**Comment by pvmraghunandan** [comment]
@minherz works fine with latest SDK. Able to see the logs in Cloud Logging.

**Comment by minherz** [comment]
Thank you for the confirmation. I am closing the issue then as fixed.
