### ISSUE TITLE
`resourceType` set to global for Cloud Run

### ISSUE THREAD

**Issue by tiagob** [googleapis/java-logging-logback#66]
The `resourceType` is set to global for Cloud Run. It makes finding logs for a particular service difficult.

<img width="439" alt="Screen Shot 2020-04-03 at 2 02 31 PM" src="https://user-images.githubusercontent.com/1031522/78409826-8cd20980-75bf-11ea-8c2c-9b0464e3948b.png">

I'm expecting

<img width="481" alt="Screen Shot 2020-04-03 at 3 00 36 PM" src="https://user-images.githubusercontent.com/1031522/78409835-93f91780-75bf-11ea-8802-7db87bfce5e7.png">

#### Environment details

1. Service: Cloud Run "run.googleapis.com/client-version: 281.0.0"
1. Java version: openjdk:11-jre-slim from Docker
1. logging-logback version(s): 0.116.0-alpha

#### Steps to reproduce

We have Cloud Run setup with ktor in kotlin. Our `logback.xml` is as follows.

#### Code example

```xml
<configuration>
    <!-- Stack Driver Appender -->
    <!-- See Config here: https://cloud.google.com/logging/docs/setup/java#wzxhzdk57wzxhzdk58logback_appender_for_product_name -->
    <appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender">
        <flushLevel>WARN</flushLevel> <!-- Optional : default ERROR -->
    </appender>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <!-- Add Console output for local dev, stacktraces for GCP Error Reporting -->
        <appender-ref ref="STDOUT"/>
        <!-- Add Cloud Appender to root output, stacktraces for GCP Logging -->
        <!-- https://cloud.google.com/logging/docs/setup/java#wzxhzdk57wzxhzdk58logback_appender_for_product_name -->
        <appender-ref ref="CLOUD" />
    </root>
</configuration>
```

#### External references such as API reference guides

- [Cloud Run Logging](https://cloud.google.com/run/docs/logging)
- [Cloud Logging Java](https://cloud.google.com/logging/docs/setup/java)

**Comment by tiagob** [comment]
Both appenders show up in Cloud Logging. STDOUT has the resource_type correctly set but doesn't have severity. CLOUD has severity but doesn't have resource_type. Ideally either approach would work.

**Comment by suraj-qlogic** [comment]
@tiagob Can you try below configuration.

`logback.xml`
```
<configuration>
    <!-- Stack Driver Appender -->
    <!-- See Config here: https://cloud.google.com/logging/docs/setup/java#wzxhzdk57wzxhzdk58logback_appender_for_product_name -->
    <appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender">
        <flushLevel>WARN</flushLevel> <!-- Optional : default ERROR -->
	<resourceType>cloud_run_revision</resourceType>
    </appender>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <!-- Add Console output for local dev, stacktraces for GCP Error Reporting -->
        <appender-ref ref="STDOUT"/>
        <!-- Add Cloud Appender to root output, stacktraces for GCP Logging -->
        <!-- https://cloud.google.com/logging/docs/setup/java#wzxhzdk57wzxhzdk58logback_appender_for_product_name -->
        <appender-ref ref="CLOUD" />
    </root>
</configuration>
```
For `cloud_run_revision` resources type following Environment variables is required to set for logging:

**GCP_PROJECT :** The current GCP project ID.
**K_SERVICE :** The name of the function resource.
**K_REVISION	:** The version identifier of the function.
**K_CONFIGURATION :** Configuration which created monitor revision value.

**Comment by tiagob** [comment]
This worked. Thank you @suraj-qlogic !

Would be nice if STDOUT included severity so we wouldn't need both logger types
