### ISSUE TITLE
WriteOption resource attribute test case work on GCE and locally

### ISSUE THREAD

**Issue by suraj-qlogic** [googleapis/java-logging-logback#72]
https://github.com/googleapis/java-logging-logback/blob/0e7d5386065df640ce80c06bc85c8e6bbf1c0b50/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java#L190-L206

**Comment by minherz** [comment]
Hello, Would you be kind to elaborate the problem?

**Comment by minherz** [comment]
Confirmed that all tests pass when run on the local environment and in GCE environment
