### ISSUE TITLE
Using redirectToStdout results in IllegalArgumentException: project ID is required

### ISSUE THREAD

**Issue by drabiger** [googleapis/java-logging-logback#930]
My use case is to test changes in configuration of my logging on my local machine before deploying it to the Google Cloud. I.e., I do not have a GCP environment, no project ID, and no Google Logging API to connect to.

My assumption was that by setting `redirectToStdout` to `true`, I would be able to do exactly that. Please correct me if I am wrong, here.

However, when I ran the configuration below, I received an exception (below, as well) referring to the fact that I didn't set a project ID. 

#### Environment details
Java version: Java 11
Version: 0.129.0-alpha
#### logback.xml

```xml
    <appender name="CONSOLE" class="com.google.cloud.logging.logback.LoggingAppender">
        <redirectToStdout>true</redirectToStdout>
    </appender>
    <root>
        <level value="info" />
        <appender-ref ref="CONSOLE" />
    </root>
```

#### Stack trace
```
14:48:36,515 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.google.cloud.logging.logback.LoggingAppender]
14:48:36,534 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
14:48:36,970 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@28:16 - RuntimeException in Action for tag [appender] java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
    at java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
    at  at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
    ...
```

**Comment by drabiger** [comment]
Cross-referencing a question on StackOverflow: https://stackoverflow.com/questions/74432806/google-loggingappender-and-stdout

**Comment by losalex** [comment]
@drabiger , thanks a lot for filing this issue. Indeed, `projectID` is required since we use it to generate a logName which is mandatory parameter in all structured logging output. Would you be able to confirm that providing just `projectID` resolves a matter?

**Comment by drabiger** [comment]
Yes, I can confirm that by setting an arbitrary project id, e.g. using,
```
<redirectToStdout>true</redirectToStdout>
<logDestinationProjectId>TEST</logDestinationProjectId>
```
no errors are thrown, and I can see JSON on stdout.

**Comment by losalex** [comment]
Thank you @drabiger for confirming this - do you believe we can close this issue?

**Comment by drabiger** [comment]
Yes, thank you.
