### ISSUE TITLE
Structured log using LoggingAppender

### ISSUE THREAD

**Issue by Kamui123** [googleapis/java-logging-logback#990]
Hi,

Is it possible to create structured log using LoggingAppender?
I managed to do it using ch.qos.logback.core.ConsoleAppender and net.logstash.logback.encoder.LogstashEncoder
```
<appender name="LOGBOOK" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
</appender>
```

but now instead of logging it to console I would like to use specific named log to separate it from stdout.
```
<appender name="LOGBOOK" class="com.google.cloud.spring.logging.LoggingAppender">
    <log>logbook</log>
</appender>
```
This configuration works but logs are not structure. Log json is printed as string.

**Comment by losalex** [comment]
Thanks @Kamui123 for opening this issue. When you mentioned "Log json is printed as string", can you please share any screenshot how you see it in Log Explorer?

**Comment by Kamui123** [comment]
Sample entry
![image](https://user-images.githubusercontent.com/40736130/214119769-a253ae6f-f1b5-44b1-9a2b-99554fb25b84.png)

**Comment by losalex** [comment]
Thanks @Kamui123 for sharing the output from Log Explorer. Indeed, looking into code it seems we do not support today structured JSON payload and use [ILoggingEvent. getFormattedMessage](https://github.com/googleapis/java-logging-logback/blob/b427a067aad3b4490f32ef475ecc835d4f714312/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L469) to retrieve string payload and embed it into a `jsonPayload`. 
It seems that `ILoggingEvent` does not provide built-in support for JSON either, so the only way to make it work is to try to detect if given message string is actually a valid JSON (thus it could be converted and embedded into `jsonPayload`). I believe the only way to make it work today is by using [LoggingEventEnhancer](https://github.com/googleapis/java-logging-logback/blob/b427a067aad3b4490f32ef475ecc835d4f714312/src/main/java/com/google/cloud/logging/logback/LoggingEventEnhancer.java#L26) - this way you can add a custom code to detect if `ILoggingEvent` message is indeed JSON and if yes, you could replace `jsonPayload` field for LogEntry currently prepared by calling to `LogEntry.Builder.setPayload` with `Payload.JsonPayload` object (you can see [tests](https://github.com/googleapis/java-logging-logback/blob/b427a067aad3b4490f32ef475ecc835d4f714312/src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java#L67) on how `Payload.JsonPayload` can be created).

**Comment by losalex** [comment]
Closing this issue due to staleness and lack of response - feel free to reactivate or comment
